on: [push]

jobs:
  latest_job:
    runs-on: ubuntu-latest
    steps:
    - name: Latest tag
      uses: EndBug/latest-tag@v1.5.1
      with:
        # You can change the name of the tag or branch with this input.
        # Default: 'latest'
        ref: latest

        # If a description is provided, the action will use it to create an annotated tag. If none is given, the action will create a lightweight tag.
        # Default: ''
        description: Description for the tag

        # Force-update a branch instead of using a tag.
        # Default: false
        force-branch: true
