on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: jacklehamster/hello-world-javascript-action@latest
        with:
          who-to-greet: ${{ github.repository}}
